### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by saharahmadisohraviyeh** [hubertjb/dl-eeg-tutorial#1]
when i run your notebook, i get:
Number of examples in each set:
Training: 18545
Validation: 4094
Test: 9850
but you reported:
Number of examples in each set:
Training: 1020
Validation: 1087
Test: 836
please, can you explain me, why this happen?

**Comment by hubertjb** [comment]
Thanks for the heads up @saharahmadisohraviyeh! It looks like I initially ran the notebook with fewer recordings (probably 3) which would explain the difference that you noticed - rerunning it gives me the same numbers as you. I just updated the tutorial accordingly.

**Comment by saharahmadisohraviyeh** [comment]
Hi,thanks for answer.good luck.
    On Sunday, May 12, 2024 at 09:14:55 PM GMT+3:30, Hubert Banville ***@***.***> wrote:  
 
 


Thanks for the heads up @saharahmadisohraviyeh! It looks like I initially ran the notebook with fewer recordings (probably 3) which would explain the difference that you noticed - rerunning it gives me the same numbers as you. I just updated the tutorial accordingly.
